"""First migrations

Revision ID: 7e73e8bb14d3
Revises: 
Create Date: 2025-08-21 11:48:42.427337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e73e8bb14d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weatherstation',
    sa.Column('stationid', sa.Integer(), nullable=False),
    sa.Column('stationname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('regio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('stationid')
    )
    op.create_table('measurement',
    sa.Column('measurementid', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('groundtemperature', sa.Float(), nullable=True),
    sa.Column('feeltemperature', sa.Float(), nullable=True),
    sa.Column('windgusts', sa.Float(), nullable=True),
    sa.Column('windspeedbft', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('sunpower', sa.Float(), nullable=True),
    sa.Column('stationid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stationid'], ['weatherstation.stationid'], ),
    sa.PrimaryKeyConstraint('measurementid'),
    sa.UniqueConstraint('stationid', 'timestamp', sqlite_on_conflict='IGNORE')
    )
    op.create_index(op.f('ix_measurement_timestamp'), 'measurement', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_timestamp'), table_name='measurement')
    op.drop_table('measurement')
    op.drop_table('weatherstation')
    # ### end Alembic commands ###
